# -*- coding: UTF-8 -*-
HTTP_PORT = 8087

DEBUG = False
ASSETS_DEBUG = False

SECRET_KEY = '4sqawsecretkey'

CACHE_TYPE = 'redis'
CACHE_DATABASE = 1

MONGODB_DATABASE = 'fsqaway'

SENTRY_DSN = ''
USE_SENTRY = False

FOURSQUARE_CLIENT_ID = 'IDPE2SQR03MVNOU2IOA0K0LLNBYGAKSQ1YZQNB1GQI3ZK4HT'
FOURSQUARE_CLIENT_SECRET = 'CCX1NM1GGCQQUFHBGZXEI3X1LU04WTUUTX2VDF5TSHUBRJ00'

CATEGORIES_LIST_CACHE_TIMEOUT = 8 * 3600

GEVENT_POOL_SIZE = 10

ALLOWED_USERS = (
    '23245433',  # Sergey Parshukov
    '17699551',  # Tyoma Kazakov
)

try:
    from local_config import *
except ImportError:
    pass
