# -*- coding: UTF-8 -*-
HTTP_PORT = 8087

DEBUG = False

CACHE_TYPE = 'redis'

SENTRY_DSN = ''
USE_SENTRY = False

FOURSQUARE_CLIENT_ID = 'IDPE2SQR03MVNOU2IOA0K0LLNBYGAKSQ1YZQNB1GQI3ZK4HT'
FOURSQUARE_CLIENT_SECRET = 'CCX1NM1GGCQQUFHBGZXEI3X1LU04WTUUTX2VDF5TSHUBRJ00'

# SEARCH_CACHE_TIMEOUT = 1800
CATEGORIES_LIST_CACHE_TIMEOUT = 8 * 3600

GEVENT_POOL_SIZE = 10

try:
    from local_config import *
except ImportError:
    pass
